--1. list of all product categories, along with the total revenue generated by each category
SELECT p.category_hierarchy,
       SUM(o.total_amount) AS revenue
FROM ec_datamart.clean_products_inventory AS p
LEFT JOIN  ec_datamart.clean_orders AS o
ON p.prod_id=o.product_id
GROUP BY p.category_hierarchy
--2. Top 5 highest-grossing products.
SELECT TOP  5 p.product_name,
       SUM(o.total_amount) AS revenue
FROM ec_datamart.clean_products_inventory AS p
LEFT JOIN  ec_datamart.clean_orders AS o
ON p.prod_id=o.product_id
GROUP BY p.product_name
ORDER BY SUM(o.total_amount) DESC;
--3.Zero sale product
SELECT p.product_name,
       SUM(o.total_amount) AS revenue
FROM ec_datamart.clean_products_inventory AS p
LEFT JOIN  ec_datamart.clean_orders AS o
ON p.prod_id=o.product_id
GROUP BY p.product_name
HAVING  SUM(o.total_amount) IS NULL OR SUM(o.total_amount)=0
ORDER BY SUM(o.total_amount) ASC;
--4.State or city buys the most from a specific category
WITH cte_city AS(SELECT c.city,
      p.product_name,
      p.category_hierarchy,
       SUM(o.total_amount) AS revenue
FROM ec_datamart.clean_products_inventory AS p
 JOIN  ec_datamart.clean_orders AS o
ON p.prod_id=o.product_id
 JOIN  ec_datamart.clean_customers AS c
 ON c.cust_id=o.customer_id
 GROUP BY  c.city,
      p.product_name,
      p.category_hierarchy)
      SELECT 
      city,
      ROW_NUMBER()OVER (PARTITION BY CITY ORDER BY revenue desc),
      product_name,
      category_hierarchy,
      revenue
      FROM cte_city;
     

--5.Product category generating the most revenue specifically among our 'GOLD' and 'PLATINUM' tier customers
WITH cte_loyalty AS
(SELECT c.loyalty_tier,
         p.category_hierarchy,
         SUM(o.total_amount) AS revenue
FROM ec_datamart.clean_products_inventory AS p
 JOIN  ec_datamart.clean_orders AS o
ON p.prod_id=o.product_id
 JOIN  ec_datamart.clean_customers AS c
 ON c.cust_id=o.customer_id
 GROUP BY  c.loyalty_tier,
       p.category_hierarchy)
 SELECT loyalty_tier,
         category_hierarchy,
          revenue
          FROM cte_loyalty
        WHERE loyalty_tier IN ('GOLD','PLATINUM')
        ORDER BY  revenue DESC;
        
--6. Month over month revenue analysis
   WITH cte_month AS (     
         SELECT DATENAME(MONTH,o.order_date) AS months
             ,SUM(o.total_amount) AS revenue
             ,YEAR(o.order_date) order_year
          
             FROM ec_datamart.clean_products_inventory AS p
             JOIN  ec_datamart.clean_orders AS o
             ON p.prod_id=o.product_id
              GROUP BY MONTH(o.order_date)
                       ,YEAR(o.order_date)
                        ,DATENAME(MONTH,o.order_date))
                       
           SELECT months
                  ,revenue
                 ,LAG(revenue,1) OVER(ORDER BY order_year,months) previous_revenue
                 ,(revenue-LAG(revenue,1) OVER(ORDER BY order_year,months))  dif_revenue
           FROM cte_month ;

--7.Days between customer purchases
WITH cte_customers AS (
SELECT c.cust_id,
      o.order_date,
     SUM(o.total_amount) AS revenue
 FROM  ec_datamart.clean_orders AS o
RIGHT JOIN  ec_datamart.clean_customers AS c
 ON c.cust_id=o.customer_id
 GROUP BY  c.cust_id
      , o.order_date)
    SELECT 
      cust_id,
      order_date,
      LAG(order_date,1)OVER (PARTITION BY cust_id ORDER BY order_date ASC) AS previous_day,
    
   DATEDIFF(day,LAG(order_date,1)OVER (PARTITION BY cust_id ORDER BY order_date ASC),order_date) AS days_btw_orders,
     revenue
      FROM cte_customers;
  --8.Customer lifetime value   
  WITH cte_expenditure AS(
  SELECT c.cust_id
        ,c.loyalty_tier
      ,SUM(o.total_amount) AS total_spend
 FROM  ec_datamart.clean_orders AS o
RIGHT JOIN  ec_datamart.clean_customers AS c
 ON c.cust_id=o.customer_id
 GROUP BY  c.cust_id,c.loyalty_tier)
     SELECT 
        
         cust_id
        ,CASE
        WHEN total_spend <500 THEN 'VIP'
        WHEN total_spend BETWEEN 500 AND 1000 THEN  'GOLD'
        WHEN total_spend BETWEEN 1000 AND 2500 THEN 'STANDARD'
        ELSE 'DIAMOND'
        END AS loyalty_tier,
         total_spend
          FROM cte_expenditure
          ORDER BY total_spend DESC;
--9.Cumulative_revenue
 WITH cte_cumulative AS(
  SELECT c.cust_id
        , year(o.order_date) AS years
       ,DATENAME(MONTH,o.order_date) AS months
      ,SUM(o.total_amount) AS revenue
      ,MONTH(o.order_date)month_num
 FROM  ec_datamart.clean_customers AS c
LEFT JOIN  ec_datamart.clean_orders AS o
 ON c.cust_id=o.customer_id
 GROUP BY c.cust_id ,DATENAME(MONTH,o.order_date), year(o.order_date),MONTH(o.order_date))
   
   SELECT cust_id,
        months
       ,SUM(revenue) OVER(PARTITION BY cust_id ORDER BY years ,month_num ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) cumulative_revenue
       FROM cte_cumulative
     --10. Three month moving average revenue
     
     WITH cte_avg AS(
  SELECT c.cust_id
        , year(o.order_date) AS years
       ,DATENAME(MONTH,o.order_date) AS months
      ,Sum(o.total_amount) AS revenue
      ,MONTH(o.order_date)month_num
 FROM  ec_datamart.clean_customers AS c
LEFT JOIN  ec_datamart.clean_orders AS o
 ON c.cust_id=o.customer_id
 GROUP BY c.cust_id ,DATENAME(MONTH,o.order_date), year(o.order_date),MONTH(o.order_date))
   
   SELECT cust_id
         ,months
       ,(revenue) OVER(PARTITION BY cust_id ORDER BY years ,month_num ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) cumulative_avg_revenue
    FROM cte_avg;

    --11.Top spenders by month

      WITH cte_spenders  AS(
  SELECT c.cust_id
       ,DATENAME(MONTH,o.order_date) AS months
      ,SUM(o.total_amount) AS total_expense
      ,MONTH(o.order_date)month_num
      ,YEAR(o.order_date)year_num
 FROM  ec_datamart.clean_customers AS c
LEFT JOIN  ec_datamart.clean_orders AS o
 ON c.cust_id=o.customer_id
 GROUP BY c.cust_id ,DATENAME(MONTH,o.order_date), year(o.order_date),MONTH(o.order_date))
   
   SELECT cust_id
         ,months
         ,total_expense
         ,RANK() OVER(PARTITION BY  year_num,month_num ORDER BY total_expense DESC  ) AS RANKS
    FROM cte_spenders ;

  --12.Customer spending quartiles 
  WITH cte_quartiles AS(
  SELECT o.customer_id
      ,Sum(o.total_amount) AS spending
  FROM  ec_datamart.clean_customers AS c
LEFT JOIN  ec_datamart.clean_orders AS o
 ON c.cust_id=o.customer_id
 GROUP BY o.customer_id)
 SELECT customer_id,spending, NTILE(4) OVER(ORDER BY spending ASC) buckets
  FROM cte_quartiles 
 --13.Finding first-purchase cohorts
  WITH cte_cohorts AS(
  SELECT o.customer_id,o.order_date,
  DATENAME(MONTH,o.order_date) AS months,
  MONTH(o.order_date) AS month_no,
  YEAR(o.order_date) AS year_no,
 ROW_NUMBER()OVER(PARTITION BY customer_id order by order_date ) rn
FROM  ec_datamart.clean_customers AS c
LEFT JOIN  ec_datamart.clean_orders AS o
 ON c.cust_id=o.customer_id
)
 SELECT customer_id,rn,order_date,months
  FROM  cte_cohorts
  WHERE rn=1;

--14.Calculating the cohort index
WITH cte_first_order AS (
    SELECT 
        customer_id,
        MIN(order_date) AS first_order_date
    FROM ec_datamart.clean_orders
    WHERE order_date IS NOT NULL
    GROUP BY customer_id
),
cte_cohort_index AS (
    SELECT 
        o.customer_id,
        o.order_date,
        f.first_order_date,
        DATEDIFF(month, f.first_order_date, o.order_date) AS cohort_index
    FROM ec_datamart.clean_orders AS o
    JOIN cte_first_order AS f
        ON o.customer_id = f.customer_id
)
SELECT 
    customer_id,
    first_order_date,
    order_date,
    cohort_index,
    CASE 
        WHEN cohort_index = 0 THEN 'Month 0 (Signup)'
        WHEN cohort_index = 1 THEN 'Month 1'
        WHEN cohort_index = 2 THEN 'Month 2'
        WHEN cohort_index = 3 THEN 'Month 3'
        ELSE 'Month 4+'
    END AS cohort_label
FROM cte_cohort_index;

--15.Inventory valuation & capital tied up
     
   SELECT category_hierarchy
  ,SUM(stock_count *  cost_price) AS total_stock
      FROM ec_datamart.clean_products_inventory AS p
           LEFT JOIN  ec_datamart.clean_orders AS o
           ON p.prod_id=o.product_id
           GROUP BY category_hierarchy
            ORDER BY total_stock DESC;  

  --16.Left stock
  SELECT 
     p.product_name,
     p.category_hierarchy,
     p.stock_count
              
     FROM ec_datamart.clean_products_inventory AS p
     LEFT JOIN  ec_datamart.clean_orders AS o
    ON p.prod_id=o.product_id
    WHERE order_id IS NULL

--17.Products ranked by total website events and stock count
SELECT
    p.product_name,
    COUNT(w.event_id) AS total_events,
    p.stock_count
FROM ec_datamart.clean_products_inventory AS p
JOIN ec_datamart.clean_website_events AS w
    ON p.prod_id = w.new_product_id
GROUP BY 
    p.product_name,
    p.stock_count
ORDER BY 
    total_events DESC;

--18.Shipping fulfillment duration
SELECT 
    carrier,
    AVG(calculated_days_to_deliver) AS avg_delivery_days
FROM ec_datamart.clean_shipping_logs
GROUP BY carrier;

--19.Shipping status breakdown
SELECT 
    status_log_clean,
   COUNT(order_ref) AS no_orders
FROM ec_datamart.clean_shipping_logs
GROUP BY status_log_clean;

 --20.Delayed shipments count and tracking by carrier
 SELECT 
    carrier,
    COUNT(order_ref) AS delayed_orders_count
FROM ec_datamart.clean_shipping_logs
WHERE (actual_days_to_deliver - estimated_days_to_deliver) > 0
GROUP BY carrier
ORDER BY delayed_orders_count DESC;

 --21. Traffic Source Performance
  SELECT 
   traffic_source,
   COUNT(event_id) AS event_id_count
FROM ec_datamart.clean_website_events 
GROUP BY traffic_source
ORDER BY COUNT(event_id)DESC;

 --22.Device and OS breakdown
  SELECT device_type
         ,os
         ,COUNT(visitor_id) AS visits
   
FROM ec_datamart.clean_website_events 
GROUP BY  device_type
         ,os
ORDER BY COUNT(visitor_id) DESC;
